In [1]:
import pandas as pd

In [5]:
data = {
    'Major' : ['IT','CS','MIS','Nan','CS','MIS','Nan','CS','Nan'],
    'Course Name' : ['Introduction to IT','Programming Fundamentals','Introduction to MIS','Database Management','Data Structures','Systems Analysis and Design','Network Security','Algorithms','Nan'],
    'Level' : [100,100,100,200,'Nan',200,300,300,'Nan']
}

df = pd.DataFrame(data)
df

  Major                  Course Name Level
0    IT           Introduction to IT   100
1    CS     Programming Fundamentals   100
2   MIS          Introduction to MIS   100
3   Nan          Database Management   200
4    CS              Data Structures   Nan
5   MIS  Systems Analysis and Design   200
6   Nan             Network Security   300
7    CS                   Algorithms   300
8   Nan                          Nan   Nan

In [6]:
df.describe()

       Major         Course Name  Level
count      9                   9      9
unique     4                   9      4
top       CS  Introduction to IT    100
freq       3                   1      3

In [14]:
df['Level'] = df['Level'].astype(float)
df

  Major                  Course Name  Level
0    IT           Introduction to IT  100.0
1    CS     Programming Fundamentals  100.0
2   MIS          Introduction to MIS  100.0
3   Nan          Database Management  200.0
4    CS              Data Structures    NaN
5   MIS  Systems Analysis and Design  200.0
6   Nan             Network Security  300.0
7    CS                   Algorithms  300.0
8   Nan                          Nan    NaN

In [11]:
df.head(4)

  Major               Course Name  Level
0    IT        Introduction to IT  100.0
1    CS  Programming Fundamentals  100.0
2   MIS       Introduction to MIS  100.0
3   Nan       Database Management  200.0

In [13]:
df = df.dropna(how='all')
df

  Major                  Course Name  Level
0    IT           Introduction to IT  100.0
1    CS     Programming Fundamentals  100.0
2   MIS          Introduction to MIS  100.0
3   Nan          Database Management  200.0
4    CS              Data Structures    NaN
5   MIS  Systems Analysis and Design  200.0
6   Nan             Network Security  300.0
7    CS                   Algorithms  300.0
8   Nan                          Nan    NaN